using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Together.Client;
using Together.Client.Storage;
using MudBlazor.Services;
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddMudServices();
builder.Services.AddScoped<BrowserStore>();
var apiBaseUrl = builder.Configuration["ApiBaseUrl"];
builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(string.IsNullOrWhiteSpace(apiBaseUrl) ? builder.HostEnvironment.BaseAddress : apiBaseUrl) });
builder.Services.AddScoped<ApiHttp>();
builder.Services.AddScoped<AuthClient>();
builder.Services.AddScoped<ApiTripStore>();
await builder.Build().RunAsync();
