CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE trips (
        "Id" uuid NOT NULL,
        "OwnerId" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "Adults" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "Revision" bigint NOT NULL,
        CONSTRAINT "PK_trips" PRIMARY KEY ("Id"),
        CONSTRAINT ck_trips_adults CHECK ("Adults" BETWEEN 1 AND 10),
        CONSTRAINT ck_trips_dates CHECK ("EndDate" > "StartDate"),
        CONSTRAINT ck_trips_name CHECK (char_length("Name") BETWEEN 1 AND 100),
        CONSTRAINT ck_trips_revision CHECK ("Revision" >= 0),
        CONSTRAINT "FK_trips_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE trip_children (
        "TripId" uuid NOT NULL,
        "Position" integer NOT NULL,
        "Age" integer NOT NULL,
        CONSTRAINT "PK_trip_children" PRIMARY KEY ("TripId", "Position"),
        CONSTRAINT ck_trip_children_age CHECK ("Age" BETWEEN 0 AND 17),
        CONSTRAINT "FK_trip_children_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE trip_selected_criteria (
        "TripId" uuid NOT NULL,
        "Criterion" character varying(32) NOT NULL,
        "Position" integer NOT NULL,
        CONSTRAINT "PK_trip_selected_criteria" PRIMARY KEY ("TripId", "Criterion"),
        CONSTRAINT ck_selected_criteria_value CHECK ("Criterion" IN ('budget','travel','transfers','kitchen','crib','playground','distance')),
        CONSTRAINT "FK_trip_selected_criteria_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE variants (
        "Id" uuid NOT NULL,
        "TripId" uuid NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Destination" character varying(150) NOT NULL,
        "Accommodation" character varying(150) NOT NULL,
        "SourceUrl" character varying(2048) NOT NULL,
        "RoadDescription" character varying(2000) NOT NULL,
        "Notes" character varying(2000) NOT NULL,
        "TravelMinutes" integer,
        "Transfers" integer,
        "Kitchen" character varying(7) NOT NULL,
        "Crib" character varying(7) NOT NULL,
        "Playground" character varying(7) NOT NULL,
        "DistanceMeters" integer,
        "DistanceTarget" character varying(100) NOT NULL,
        "NeedsBudgetReview" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "Revision" bigint NOT NULL,
        CONSTRAINT "PK_variants" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_variants_TripId_Id" UNIQUE ("TripId", "Id"),
        CONSTRAINT ck_variants_amenities CHECK ("Kitchen" IN ('yes','no','unknown') AND "Crib" IN ('yes','no','unknown') AND "Playground" IN ('yes','no','unknown')),
        CONSTRAINT ck_variants_distance CHECK ("DistanceMeters" IS NULL OR "DistanceMeters" BETWEEN 0 AND 1000000),
        CONSTRAINT ck_variants_revision CHECK ("Revision" >= 0),
        CONSTRAINT ck_variants_transfers CHECK ("Transfers" IS NULL OR "Transfers" BETWEEN 0 AND 20),
        CONSTRAINT ck_variants_travel_minutes CHECK ("TravelMinutes" IS NULL OR "TravelMinutes" BETWEEN 0 AND 100000),
        CONSTRAINT "FK_variants_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE trip_selected_variants (
        "TripId" uuid NOT NULL,
        "VariantId" uuid NOT NULL,
        "Position" integer NOT NULL,
        CONSTRAINT "PK_trip_selected_variants" PRIMARY KEY ("TripId", "VariantId"),
        CONSTRAINT "FK_trip_selected_variants_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_trip_selected_variants_variants_TripId_VariantId" FOREIGN KEY ("TripId", "VariantId") REFERENCES variants ("TripId", "Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE TABLE variant_expenses (
        "VariantId" uuid NOT NULL,
        "Category" character varying(32) NOT NULL,
        "AmountKopecks" bigint,
        CONSTRAINT "PK_variant_expenses" PRIMARY KEY ("VariantId", "Category"),
        CONSTRAINT ck_variant_expenses_amount CHECK ("AmountKopecks" IS NULL OR "AmountKopecks" BETWEEN 0 AND 10000000000),
        CONSTRAINT ck_variant_expenses_category CHECK ("Category" IN ('travel','accommodation','food','localTransport','entertainment','other')),
        CONSTRAINT "FK_variant_expenses_variants_VariantId" FOREIGN KEY ("VariantId") REFERENCES variants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_trip_selected_criteria_TripId_Position" ON trip_selected_criteria ("TripId", "Position");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_trip_selected_variants_TripId_Position" ON trip_selected_variants ("TripId", "Position");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    CREATE INDEX "IX_trips_OwnerId_UpdatedAt" ON trips ("OwnerId", "UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081329_InitialPostgreSql') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917081329_InitialPostgreSql', '10.0.10');
    END IF;
END $EF$;
COMMIT;

